import os
import pandas as pd

from langchain import OpenAI
from langchain.chat_models import ChatOpenAI
from langchain.agents import create_pandas_dataframe_agent



API_KEY = os.environ["OPENAI_API_KEY"]


def create_agent(df: pd.DataFrame):
    """
    Create an agent that can access and use a large language model (LLM).

    Args:
        filename: The path to the CSV file that contains the data.

    Returns:
        An agent that can access and use the LLM.
    """

    # Create an OpenAI object.
    llm = OpenAI(temperature=0.0, openai_api_key=API_KEY)

    # Create a Pandas DataFrame agent.
    return create_pandas_dataframe_agent(llm, df, verbose=False)

def summary_agent(df: pd.DataFrame):
    agent = create_agent(df)
    prompt =(
        """
        Write few lines of description of the csv file and then make a list of all the columns with a brieve description of each column and their dtype. 
        Here is an example with a macdonald.csv file :
        
        The McDonald's revenue dataset encompasses a collection of historical financial data from 1999 to 2023, offering a comprehensive overview 
        of the company's earnings over time. It provides detailed information on the revenue generated by McDonald's, reflecting the monetary value 
        of its sales and transactions within the specified period.
        
        Here is the list of columns with their description :
        - mcdo_id: unique identifier for each macdonald (int64) 
        - mcdo_employee_id: unique identifier for each macdonald employee (int64) 

        """
    )
    response = agent.run(prompt)
    return response 
